---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mysql-volsync
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: mysql-volsync-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: mysql-volsync-{{name}}
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: "{{name}}"
        argocd.argoproj.io/skip-reconcile: "true"
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/CSA-RH/argodemo3_mysql-volsync.git
        targetRevision: main
        path: kustomize/overlays/prod
      destination:
        server: https://kubernetes.default.svc
        namespace: mysql-volsync
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
